apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: audio-to-text-y1731927990785 
  janus-idp.io/tekton: audio-to-text-y1731927990785
  backstage.io/kubernetes-id: audio-to-text-y1731927990785
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: audio-to-text-y1731927990785
resources: 
- application-dev.yaml