---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: audio-to-text-y1731927990785
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audio-to-text-y1731927990785 
  name: audio-to-text-y1731927990785
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi